---
# tasks file for roles/osp-instance-delete
#  - name: Fetch Instance Info
#  - name: Delete instances
- name: Delete server instances
  os_server:
    cloud:            "{{ openstack_cloud                           | default('openstack') }}"
    name:             "{{ __openstack_server.name }}"
    state:            "{{ openstack_server_state                    | default(__openstack_server.state) | default('present') }}"
    image:            "{{ __openstack_server.image                  | default('rhel-guest') }}"
    flavor:           "{{ __openstack_server.flavor                 | default('m1.medium') }}"
    key_name:         "{{ __openstack_server.key_name               | default('ansible_ssh_key') }}"
    wait:             "{{ __openstack_server.wait                   | default('yes') }}"
    security_groups:  "{{ __openstack_server.security_group }}"
    delete_fip:       "{{__openstack_server.delete_fip              | default(true) }}"
#    meta: "group={{ __openstack_server.meta.group }},deployment_name={{ __openstack_server.meta.deployment_name }}"
    nics:
      - net-name: int_network
      #    - net-name: ext_network
  loop: "{{ osp_servers }}"      
  loop_control:
    loop_var: __openstack_server
  async: 900
  poll: 0
  register: r_instances

- name: Wait for async OSP instance delete to complete
  async_status: "jid={{ item.ansible_job_id }}"
  register: r_wait
  until: r_wait.finished
  retries: 900
  loop: "{{ r_instances.results }}"
