- hosts: workstation
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://frontend1/ping"
      return_content: yes
      status_code: 200
    register: webpage
  - debug:
      msg: "{{ webpage.content }}"

  roles:
    - name: osp-instance-delete
      tags:
        - osp.smoke
      when: "'Ansible has done its job' not in webpage.content"
