- hosts: workstation
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://frontend1/ping"
      return_content: yes
      status_code: 200
    register: webpage
  - debug:
      msg: "{{ webpage.content }}"

#  roles:
  - name: Fail if 'Ansible has done its job' is not in the page content
#    - role: osp-instance-delete
    fail:
    include: site-osp-delete.yml 
    when: "'Ansible has done its job' not in webpage.content"
