- hosts: workstation
  gather_facts: false
  tasks:
  - name: Curl website
    uri:
      url: "http://frontend1/ping"
      return_content: yes
      status_code: 200
    register: webpage
  - debug:
      msg: "{{ webpage[0].content }}"

#  - name: Fail if 'Ansible has done its job' is not in the page content
#    fail:
#      msg: "Ansible failed in its work !!!"
#    when: "'Ansible has done its job' not in webpage.results[0].content"
#    tags:
#      - osp.smoke
