---
# vars file for osp.servers

openstack_server_state: absent

project_name: admin

osp_servers:
#  frontend:
  - name: frontend
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: frontend
    meta_group: frontends
    meta_deployment_name: QA
#    meta:
#      - { group: frontends, deployment_name: QA}
#  app1:
  - name: app1
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta_group: apps
    meta_deployment_name: QA
#    meta:
#      - { group: apps, deployment_name: QA}
#  app2:
  - name: app2
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: apps
    meta_group: apps
    meta_deployment_name: QA
#    meta:
#      - { group: apps, deployment_name: QA}
#  db:
  - name: db
    state: present
    image: rhel-guest
    key_name: ansible_ssh
    flavor: m1.medium
    security_group: db
    meta_group: appdbs
    meta_deployment_name: QA
#    meta:
#      - { group: appdbs, deployment_name: QA}
